apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustom-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devoriales/argocd-beginner.git
    targetRevision: main
    path: module-04-deploying-applications/02-kustomize/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
